setup:
  tf_seed: 421
  precision_policy: mixed_float16
  gpus_with_memory_growth: true
  paths:
    data: &paths_data "./data"
    tensorboard: "{report_dir}"
    best: "{report_dir}/best.h5"
    ckpt: "./logs/cifar10/baseline/backup/"
    export: "{report_dir}/final"
    train_history: "{report_dir}/train-history.csv"
    valid_report: "{report_dir}/valid-report.csv"
dataset:
  load:
    name: cifar10
    data_dir: *paths_data
    splits:
      - train[:80%]
      - train[80%:]
      - test
  prepare:
    batch_size: 64
    sizes: [32, 32, 3]
    buffer_size: auto
    parallel_calls: auto
    drop_remainder: true
    task: classification
    classes: &classes 10
    keys:
      - image
      - label
    augmentation:
      policy:
        class_name: Simple
        config:
          random_generator: 10391
          constraints:
            brightness_delta: 0.2
            saturation_lower: 0.5
            saturation_upper: 1.0
            contrast_lower: 0.5
            contrast_upper: 1.5
            hue_delta: 0.0
      over: samples
      as_numpy: false
    shuffle:
      buffer_size: 1000
      seed: 4081
      reshuffle_each_iteration: true
    preprocess_fn: "keras.applications.resnet_v2.preprocess_input"
model:
  input_shape: [32, 32, 3]
  head:
    name: mc_cifar10
    units: *classes
    activation: softmax
    dropout_rate: 0.2
    kernel_regularizer: null
    kernel_initializer: null
    layer_class: dense
  backbone:
    architecture: ResNet50V2
    weights: imagenet
    pooling: avg
    trainable: false
training:
  perform: true
  loss: SparseCategoricalCrossentropy
  optimizer:
    class_name: sgd
    config: &momentum
      learning_rate: 0.1
      momentum: 0.9
      nesterov: true
  metrics:
    - SparseCategoricalAccuracy
    - SparseTopKCategoricalAccuracy
    # - precision
    # - recall
  config:
    epochs: &epochs 20
    verbose: 2
  callbacks: &callbacks
    - TerminateOnNaN
    - class_name: EarlyStopping
      config:
        patience: 50
        verbose: 1
    - class_name: ReduceLROnPlateau
      config:
        factor: 0.5
        patience: 10
        verbose: 1
    - class_name: TensorBoard
      config:
        log_dir: "./logs/"
        histogram_freq: 1
        profile_batch: 0
        write_graph: true
      override:
        log_dir: paths.tensorboard
    - class_name: CSVLogger
      config:
        filename: "./history.csv"
        append: true
      override:
        filename: paths.train_history
    - class_name: ModelCheckpoint
      config:
        verbose: 1
        filepath: "./best.h5"
        save_best_only: true
        save_weights_only: true
      override:
        filepath: paths.best
    - class_name: BackupAndRestore
      config:
        backup_dir: "/tmp/ckpt"
      override:
        backup_dir: paths.ckpt
  finetune:
    perform: true
    unfreeze:
      layers: 'conv5_block1_1_conv'
      freeze_bn: true
    optimizer:
      class_name: sgd
      config:
        <<: *momentum
        learning_rate: 0.001
    config:
      epochs: 100
      initial_epoch: *epochs
      verbose: 2
    callbacks: *callbacks
evaluation:
  task: sparse_classification_multiclass
  report_path: "{valid_report}"
