version: "2.3"
services:
  tf-experiment:
    image: ldavid/tf-experiment
    # runtime: nvidia  # when GPUs are available
    build:
      dockerfile: ./config/docker/Dockerfile
      context: .
      args:
        BASE_IMAGE: tensorflow/tensorflow:latest-gpu-jupyter
    ports:
      - "8888:8888"
      - "6006:6006"
    env_file: ./config/docker/.env
    volumes:
      - ./notebooks:/tf/notebooks
      - ./config:/tf/config
      - ./logs:/tf/logs
      - ./src:/tf/src
      - ./experiments:/tf/experiments
      - ./data:/tf/data
      - ./data/cached/.cache:/root/.cache
