setup:
  tf_seed: 724
dataset:
  load:
    name: 'voc/2007'
    data_dir: "./data"
    splits:
      - train
      - validation
      - test
  prepare:
    batch_size: 64
    sizes: &image_sizes [512, 512, 3]
    prefetch_buffer_size: auto
    parallel_calls: auto
    drop_remainder: true
    task: classification_multilabel_from_detection
    classes: &classes 20
    keys:
      - image
      - objects.label
    shuffle:
      seed: 8124
      buffer_size: 10000
      splits:
        - train
    augmentation:
      splits:
        - train
        # - validation
        # - test
    pad_values: [0, -1]
model:
  name: ml_voc07
  input_shape: *image_sizes
  head:
    units: *classes
    activation: sigmoid
training:
  loss: BinaryCrossentropy
  metrics:
    - BinaryAccuracy
    - Precision
    - Recall
evaluation:
  task: classification_multilabel
