training:
  optimizer:
    class_name: sgd
    config:
      learning_rate: 0.01
      momentum: 0.9
      nesterov: true
  finetune:
    optimizer:
      class_name: sgd
      config:
        learning_rate: 0.01
        momentum: 0.9
        nesterov: true
