setup:
  tf_seed: 41820
  # precision_policy: mixed_float16
  # gpus_with_memory_growth: true
  paths:
    data: &paths_data "/data"
    export: "/tf/logs/models/pascal-2012/rn101/exported"
    report: "{report_dir}/report.csv"
dataset:
  load:
    name: 'voc/2012'
    data_dir: *paths_data
    splits:
      - train
      - validation
      - test
  prepare:
    batch_size: 64
    sizes: [512, 512, 3]
    prefetch_buffer_size: auto
    parallel_calls: auto
    pad_values: -1.0
    pad_drop_remainder: true
    task: object_detection
    classes: &classes 20
    keys:
      - image
      - objects.bbox
      - objects.label
    augmentation:
      policy: Default
      over: samples
    shuffle:
      buffer_size: 1000
      seed: 4081
      reshuffle_each_iteration: true
    preprocess_fn: "keras.applications.resnet_v2.preprocess_input"
evaluation:
  report_path: "{report}"
  explanations:
    inference:
      batch_size: 64
      threshold: 0.5
    methods:
      - cam
      - minmax_cam
      - d_minmax_cam
    ckpt_dir: '/data/cached/explaining'
  splits:
    train: true
    validation: true
    test: false
