dataset:
  prepare:
    preprocess_fn: "keras.applications.resnet_v2.preprocess_input"
model:
  backbone:
    architecture: ResNet101V2
training:
  finetune:
    unfreeze:
      layers: conv4_block10_out
