model:
  backbone:
    weights: imagenet
training:
  perform: false
  config:
    epochs: &epochs 0
  finetune:
    perform: true
    config:
      epochs: 100
      initial_epoch: *epochs
    unfreeze:
      freeze_bn: false
