dataset:
  prepare:
    augmentation:
      policy:
        class_name: Simple
        config:
          random_generator: 10391
          constraints:
            brightness_delta: 0.2
            saturation_lower: 0.5
            saturation_upper: 1.0
            contrast_lower: 0.5
            contrast_upper: 1.5
            hue_delta: 0.0
      over: samples
